inherits_from: default
standards_as_claude_code_skills: true

exclude_inherited_files:
  - standards/backend/*
  - standards/frontend/*
  - standards/global/coding-style.md
  - standards/global/conventions.md
  - standards/global/tech-stack.md
  - standards/global/validation.md
 

