inherits_from: default

exclude_inherited_files:
  - standards/backend/*
  - standards/frontend/*
  - standards/global/coding-style.md
  - standards/global/conventions.md
  - standards/global/error-handling.md
  - standards/global/tech-stack.md
  - standards/global/validation.md
 